version: '3.8'
services:
  dynamodb-local:
    build:
      context: .
      dockerfile: Dockerfile.dynamodb
    image: amazon/dynamodb-local:latest
    container_name: dynamodb-local
    ports:
      - '8000:8000'
    volumes:
      - dynamodb-data:/home/dynamodblocal
      - ./models:/models
      - ./seeds:/seeds
    command: ['-jar', 'DynamoDBLocal.jar', '-sharedDb', '-dbPath', '/home/dynamodblocal']

  dynamodb-admin:
    image: aaronshaf/dynamodb-admin:latest
    container_name: dynamodb-admin-ui
    ports:
      - '8001:8001'
    environment:
      DYNAMO_ENDPOINT: http://dynamodb-local:8000/
    depends_on:
      - dynamodb-local

volumes:
  dynamodb-data:
